# Generated by Django 5.1.7 on 2025-03-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
